{
    image: microsoft/dotnet

    stages: 
      - test
      - analyze
    
    unit test:
      stage: test
      script:
      - dotnet test
    
  "deploy": [
    {
      "provider": "pages",
      "skip_cleanup": true,
      "keep_history": true,
      "on": {
        "branch": [
          "gh-pages"
        ]
      },
      "token": "$Travis_CI_Secret"
    }
  ]
}
